### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by cletuskingdom** [tonysm/rich-text-laravel#10]
Please why is this showing?

```
[InvalidArgumentException]                                                                                       
Package tonysm/rich-text-laravel has a PHP requirement incompatible with your PHP version, PHP extensions
 and Composer version
```
![image](https://user-images.githubusercontent.com/38631504/133735548-05c85bee-6313-4699-b3a4-c5ad21d0ea03.png)

**Comment by kyranb** [comment]
This package requires  `"php": "^8.0",` as defined in `composer.json`.

Check what you are running with `php -v`

**Comment by cletuskingdom** [comment]
![image](https://user-images.githubusercontent.com/38631504/133738161-308a17f4-9971-444b-abe3-d4a73c3cd48b.png)

here's what i wrote

**Comment by kyranb** [comment]
You'll need to update the version of PHP you are running to be version 8 to use this package.

**Comment by cletuskingdom** [comment]
Here's what i get after updating to php v8
![image](https://user-images.githubusercontent.com/38631504/133740285-1a2efa87-3806-4200-9513-bcd5fc67457b.png)

**Comment by kyranb** [comment]
That’s not updating to php 8, you’re just stipulating that your php project will work with that version or hire.

**Comment by cletuskingdom** [comment]
I've updated my php version to php8

**Comment by kyranb** [comment]
That's a composer error message that you need to configure/enable the `openssl` extension to work with PHP 8, the error isn't related to this package 👍

**Comment by tonysm** [comment]
Thanks @kyranb for jumping in.

@cletuskingdom yeah, the package requires PHP 8. And it looks like Composer requires the `openssl` extension, which doesn't seem to be install on your machine. Take a look at this [SO thread](https://stackoverflow.com/questions/35249620/the-openssl-extension-is-required-for-ssl-tls-protection).

I'm closing the issue for now. If you still have trouble installing the package, please, feel free to re-open it.
