### ISSUE TITLE
Attachments that are not images throw error

### ISSUE THREAD

**Issue by mrpritchett** [tonysm/rich-text-laravel#15]
In some cases, things like CSVs, PDFs, and other file types throw this error when they are uploaded the form is submitted:

`Attempt to read property "childNodes" on null`

This is where the error occurs:

```
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/tonysm/rich-text-laravel/src/Fragment.php:78
```

**Comment by mrpritchett** [comment]
Yeah, my hope was to have specific control over the output of the upload by attaching it to the Upload model. But I can confirm by adding a check to see what the type is and only giving images an sgid I can upload files, just not with the specific output that I hoped.

**Comment by tonysm** [comment]
Hey @mrpritchett 

I have tried some advanced templating tweaks and was able to get to a really cool flow. I plan to write about it, but for the meantime, I've published the demo app.

A few interesting places to look at:

1. The rich-text blade component (the field) which hooks the Stimulus controller ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/resources/views/components/rich-text.blade.php#L9-L11))
2. The app is using Spatie's MediaLibrary for the uploads, so there's a custom media model ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/app/Models/Media.php)), also check out the overriding of the `toTrixContent` ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/app/Models/Media.php#L70-L79)) - which is used when rendering the media attachable to feed Trix - and the `richTextRender` method ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/app/Models/Media.php#L81-L87))
3. The upload handler ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/routes/web.php#L24-L38))
4. The route handler that renders the attachable ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/routes/web.php#L13-L21))
5. And, finally, the Trix Stimulus Controller ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/resources/js/controllers/trix_controller.js)) and the Attachment Uploader ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/resources/js/attachments/AttachmentUploader.js))

And [here's](https://twitter.com/tonysmdev/status/1454833040241348616) a quick demo of it working.

One interesting thing I found out is that video tags don't play really well with Trix. The editor seems to constantly re-render, so the video gets "flickering". What worked for me was generating a thumbnail for the video (using Spatie's MediaLibrary and FFMPEG, [here's the code](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/app/Models/Team.php#L54-L61)) and displaying that when the media renders in the Trix editor ([here](https://github.com/tonysm/lara-journal-rich-text-demo/blob/main/resources/views/medias/_trix-media-editor.blade.php)).

Let me know if any of this helps you.

**Comment by mrpritchett** [comment]
@tonysm We're rushing the new editor to the finish line this week, but I'm going to circle back to this next week to check out in depth. I appreciate all your hard work on this package and in responding to our GH issues. Is there a preferred way we can support your work here on GH or otherwise?
