### ISSUE TITLE
Livewire Integration Example

### ISSUE THREAD

**Issue by myregistration** [tonysm/rich-text-laravel#31]
We need a better example in the readme or video tutorial how to integrate Livewire.  Thanks!

**Comment by tonysm** [comment]
I'll see if I can work on something this weekend

**Comment by tonysm** [comment]
Also, I haven't tested it with Livewire V3 yet, so there's that...

**Comment by myregistration** [comment]
Yeah, there seems to be quite a bit of change from Livewire v2 to v3

**Comment by tonysm** [comment]
I have updated the README docs on Livewire. It only mentions that we must use entangle now instead of the previous way. I've also added an example to the Workbench application on using the package in a Livewire project.
