### ISSUE TITLE
Documentation could be clearer regarding styles

### ISSUE THREAD

**Issue by rooselle** [tonysm/rich-text-laravel#55]
Hi,

First: thanks for this package :pray: 

I've just installed it, and it took me a bit of time to figure how to display the editor with the styles (back-end developer here :grin:). I took the doc to the letter, so when I read:
> If you're using Laravel Mix/Webpack, the resources/js/trix.js file has the JS setup and the CSS import as well, so no need to use the the Blade Component.
> 
> The package also publishes a Blade Component for you which can be used inside your forms, like so:
> `<x-trix-input id="bio" name="bio" />`

I added the `<x-trix-input />` component in my blade and hope it would look great right away (since the JS and theoretically CSS import was already made). And it didn't :upside_down_face:  In the end I tried to add `<x-rich-text::styles />` and it worked! But since it was under:
> If you're using the [Importmap Laravel](https://github.com/tonysm/importmap-laravel) package

I kinda thought it didn't concern me.
Actually, no matter if you're using the Importmap package or Breeze or none, you _have_ to add `<x-rich-text::styles />`, right? I actually don't think the CSS is imported any other way, or am I missing something? :thinking:

**Comment by tonysm** [comment]
Ah, thanks! I'll fix the docs.

Yeah, in previous iterations, I was also publishing a CSS file that would be imported in the JS file... but I stopped doing that myself (as I mentioned, I use Importmap Laravel, so importing CSS files in JS files doesn't work in the real world, but it does in the bundling world).

**Comment by tonysm** [comment]
@rooselle I've pushed an update to the docs (https://github.com/tonysm/rich-text-laravel/commit/0c08cc1e84c04a5946c094b109e4e838e6a24dfd), let me know if it's better now. I'll close it for now, but pls feel free to reopen it if you think it could still be improved. And thanks for reporting it!

**Comment by rooselle** [comment]
Thanks @tonysm for the quick fix! It's perfect now :blush:
