### ISSUE TITLE
A ZIP attachment is weirdly rendered

### ISSUE THREAD

**Issue by rooselle** [tonysm/rich-text-laravel#57]
Everything works great except from one little detail: the rendering (`$model->rich_text->body->render()`) of a ZIP attachment displays `<span>⊠</span>` instead of a `figure` with a download button. In the editor it's displayed (`$model->rich_text->body->toTrixHtml()`) just as the other attachments:
```html
<figure contenteditable="false" data-trix-attachment="{&quot;contentType&quot;:&quot;application/zip&quot;,&quot;filename&quot;:&quot;foo.zip&quot;,&quot;filesize&quot;:1290774,&quot;url&quot;:&quot;https://server/foo.zip&quot;}" data-trix-content-type="application/zip" data-trix-id="123" class="attachment attachment--file attachment--zip"><figcaption class="attachment__caption"><span class="attachment__name">Foo.zip</span> <span class="attachment__size">1.23 MB</span></figcaption></figure>
```
Does this happen for someone else? Or am I missing something?

**Comment by tonysm** [comment]
Yep, you must add the `application/zip` as a supported mimetype on your config ([here](https://github.com/tonysm/rich-text-laravel/blob/main/config/rich-text-laravel.php#L37-L45)).

Unsupported uploaded files will not render by default (that's the "missing" icon you see).

Let me know if that helps! If you think there's an issue here, feel free to reopen the issue.

**Comment by rooselle** [comment]
Ohh thanks I had totally forgotten about that. However I don't think there's any indication about it in the doc, actually I don't remember where I have seen it before because I can't seem to find it in your blog posts either, so maybe I just went by myself to the vendor package config file. :) I think it would be great to mention this in the README, and also to be able to only publish the config file with: `sail artisan vendor:publish --provider=Tonysm\RichTextLaravel\RichTextLaravelServiceProvider --tag=config` (not possible at the moment). I'll try and make a PR for this when I have the time :)

Anyway that helps and it works like this!

Another thing (tell me if I should open another issue for this because it's not directly related): I saw you add a `not-prose` CSS class to attachments, why is that? I'm sure you have a good reason :slightly_smiling_face:  But I personally would benefit to not have this class, because I quite like how prose formats it and without it it's just plain text and the "Download" link is not really noticeable.

**Comment by tonysm** [comment]
@rooselle I used to mention those packages in the [Sanitization section of the docs](https://github.com/tonysm/rich-text-laravel?tab=readme-ov-file#sanitization), but I switched to reaching for Symfony's HTML Sanitizer. We need better documentation around the tags to allow tbh. There's an implementation of this in the Workbench application ([here](https://github.com/tonysm/laravel-bootcamp-blade-chirper/blob/rich-text-laravel/app/Providers/AppServiceProvider.php#L18-L22)), but I also have another example [here](https://github.com/tonysm/laravel-bootcamp-blade-chirper/blob/rich-text-laravel/app/Providers/AppServiceProvider.php#L18-L22).

I'd be up to a PR removing the Tailwind-specific classes from the package, if you feel like contributing. I'll probably remove it soon. My issue was that some of the `.trix-content` styles were conflicting with Tailwind reset and styles, especially around prose, so I reached for that. But we sure can remove those classes. You may also publish the package views and have full control over the rendered HTML there if you want to.
